#!/bin/sh
#
# /etc/init.d/bitbucket -- startup script for the Atlassian Bitbucket
#
# Written by Choi Kyung-sik <https://www.bitneer.info/contact>.
#
### BEGIN INIT INFO
# Provides:          bitbucket
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Bitbucket
# Description:       Start the Atlassian Bitbucket.
### END INIT INFO

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=bitbucket
DESC="Atlassian Bitbucket"
JVM_TMP=/tmp/bitbucket-tmp

if [ `id -u` -ne 0 ]; then
  echo "You need root privileges to run this script"
  exit 1
fi

# Make sure bitbucket is started with system locale
if [ -r /etc/default/locale ]; then
  . /etc/default/locale
  export LANG
fi

. /lib/lsb/init-functions

if [ -r /etc/default/rcS ]; then
  . /etc/default/rcS
fi

# Run Atlassian Bitbucket as this user ID and group ID
BITBUCKET_USER=bitbucket
BITBUCKET_GROUP=bitbucket

# Oracle JDK is used for JAVA_HOME
JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
export JAVA_HOME

# Directory where the Atlassian Bitbucket binary distribution resides
CATALINA_HOME=/opt/share/$NAME

# Directory for per-instance configuration files and webapps
CATALINA_BASE=/opt/share/$NAME

echo "2"

# Java options
JAVA_OPTS="-Djava.awt.headless=true"

echo "3"

if [ ! -f "$CATALINA_HOME/bin/bootstrap.jar" ]; then
  log_failure_msg "$NAME is not installed"
  exit 1
fi

if [ -z "$CATALINA_TMPDIR" ]; then
  CATALINA_TMPDIR="$JVM_TMP"
fi

# Define other required variables
CATALINA_PID="/var/run/$NAME.pid"
CATALINA_SH="$CATALINA_HOME/bin/catalina.sh"

# Look for Java Secure Sockets Extension (JSSE) JARs
if [ -z "${JSSE_HOME}" -a -r "${JAVA_HOME}/jre/lib/jsse.jar" ]; then
  JSSE_HOME="${JAVA_HOME}/jre/"
fi

catalina_sh() {
  # Escape any double quotes in the value of JAVA_OPTS
  JAVA_OPTS="$(echo $JAVA_OPTS | sed 's/\"/\\\"/g')"

  # Define the command to run Atlassian Bitbucket's catalina.sh as a daemon
  # set -a tells sh to export assigned variables to spawned shells.
  BITBUCKET_SH="set -a; JAVA_HOME=\"$JAVA_HOME\"; \
    CATALINA_HOME=\"$CATALINA_HOME\"; \
    CATALINA_BASE=\"$CATALINA_BASE\"; \
    JAVA_OPTS=\"$JAVA_OPTS\"; \
    CATALINA_PID=\"$CATALINA_PID\"; \
    CATALINA_TMPDIR=\"$CATALINA_TMPDIR\"; \
    LANG=\"$LANG\"; JSSE_HOME=\"$JSSE_HOME\"; \
    cd \"$CATALINA_BASE\"; \
    \"$CATALINA_SH\" start $@"

  # Run the catalina.sh script as a daemon
  set +e
  touch "$CATALINA_PID" "$CATALINA_BASE"/logs/catalina.out
  chown $BITBUCKET_USER "$CATALINA_PID" "$CATALINA_BASE"/logs/catalina.out
  start-stop-daemon --start -b -u "$BITBUCKET_USER" -g "$BITBUCKET_GROUP" \
    -c "$BITBUCKET_USER" -d "$CATALINA_TMPDIR" -p "$CATALINA_PID" \
    -x /bin/bash -- -c "$BITBUCKET_SH"
  status="$?"
  set +a -e
  return $status
}

case "$1" in
  start)
  if [ -z "$JAVA_HOME" ]; then
    log_failure_msg "no JDK found - please set JAVA_HOME"
    exit 1
  fi

  if [ ! -d "$CATALINA_BASE/conf" ]; then
    log_failure_msg "invalid CATALINA_BASE: $CATALINA_BASE"
    exit 1
  fi

  log_daemon_msg "Starting $DESC" "$NAME"

  if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
    --user $BITBUCKET_USER --exec "$JAVA_HOME/bin/java" \
    >/dev/null; then

    # Remove / recreate JVM_TMP directory
    rm -rf "$JVM_TMP"
    mkdir -p "$JVM_TMP" || {
      log_failure_msg "could not create JVM temporary directory"
      exit 1
    }
    chown $BITBUCKET_USER "$JVM_TMP"

    catalina_sh
    sleep 5
    if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
      --user $BITBUCKET_USER --exec "$JAVA_HOME/bin/java" \
      >/dev/null; then
      if [ -f "$CATALINA_PID" ]; then
        rm -f "$CATALINA_PID"
      fi
      log_end_msg 1
    else
      log_end_msg 0
    fi
  else
    log_progress_msg "(already running)"
    log_end_msg 0
  fi
  ;;
  stop)
  log_daemon_msg "Stopping $DESC" "$NAME"

  set +e
  if [ -f "$CATALINA_PID" ]; then
    start-stop-daemon --stop --pidfile "$CATALINA_PID" \
      --user "$BITBUCKET_USER" \
      --retry=TERM/20/KILL/5 >/dev/null
    if [ $? -eq 1 ]; then
      log_progress_msg "$DESC is not running but pid file exists, cleaning up"
    elif [ $? -eq 3 ]; then
      PID="`cat $CATALINA_PID`"
      log_failure_msg "Failed to stop $NAME (pid $PID)"
      exit 1
    fi
    rm -f "$CATALINA_PID"
    rm -rf "$JVM_TMP"
  else
    log_progress_msg "(not running)"
  fi
  log_end_msg 0
  set -e
  ;;
  status)
  set +e
  start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
    --user $BITBUCKET_USER --exec "$JAVA_HOME/bin/java" \
    >/dev/null 2>&1
  if [ "$?" = "0" ]; then
    if [ -f "$CATALINA_PID" ]; then
      log_success_msg "$DESC is not running, but pid file exists."
      exit 1
    else
      log_success_msg "$DESC is not running."
      exit 3
    fi
  else
    log_success_msg "$DESC is running with pid `cat $CATALINA_PID`"
  fi
  set -e
  ;;
  restart|force-reload)
  if [ -f "$CATALINA_PID" ]; then
    $0 stop
    sleep 1
  fi
  $0 start
  ;;
  try-restart)
    if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
      --user $BITBUCKET_USER --exec "$JAVA_HOME/bin/java" \
      >/dev/null; then
    $0 start
  fi
  ;;
  *)
  log_success_msg "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
  exit 1
  ;;
esac

exit 0
